<!DOCTYPE html>
<html>
<head>
    <title>Monthly Profit Summary - Techsoul Cyber Solutions</title>
</head>
<style type="text/css">
    body{
        font-family: 'Roboto Condensed', sans-serif;
    }
    .container{
        bottom: 50px;
    }
    .m-0{
        margin: 0px;
    }
    .p-0{
        padding: 0px;
    }
    .pt-5{
        padding-top:5px;
    }
    .mt-10{
        margin-top:10px;
    }
    .mt-25{
        margin-top:25px;
    }
    .text-center{
        text-align:center !important;
    }
    .w-100{
        width: 100%;
    }
    .w-50{
        width:50%;
    }
    .w-85{
        width:85%;
    }
    .w-15{
        width:15%;
    }
    .logo img{
        width:45px;
        height:45px;
        padding-top:30px;
    }
    .logo span{
        margin-left:8px;
        top:19px;
        position: absolute;
        font-weight: bold;
        font-size:25px;
    }
    .gray-color{
        color:#5D5D5D;
    }
    .text-bold{
        font-weight: bold;
    }
    .border{
        border:1px solid black;
    }
    table tr,th,td{
        border: 1px solid #d2d2d2;
        border-collapse:collapse;
        padding:7px 8px;
    }
    table tr th{
        background: #F4F4F4;
        font-size:15px;
    }
    table tr td{
        font-size:13px;
    }
    table{
        border-collapse:collapse;
    }
    .box-text p{
        line-height:10px;
    }
    .float-left{
        float:left;
    }
    .total-part{
        font-size:16px;
        line-height:12px;
    }
    .total-right p{
        padding-right:20px;
    }
    .page-break {
        page-break-after: always;
    }
    .footer {
        position: fixed;
        bottom: -24px;
    }

    .footer .page:after {
        text-align:left;
        content: counter(page);
    }
    .footer .caption {
        text-align:right !important;
        font-size:10px;
    }
</style>
<body>
    <div class="footer">
        @php
            $printed_by = Auth::user()->name;
            $printed_on = Carbon\carbon::now();
        @endphp
        <table style="padding-top:20px;">
            <tr style="border:none;">
                <td style="border:none;">
                    <p class="page"></p>
                </td>
                <td style="border:none;">
                    <p class="caption">generated by {{ $printed_by }} on {{ $printed_on }}</p>
                </td>
            </tr>
        </table>
        </div>
    </div>
    <div class="container">
        <div class="head-title">
            <h2 class="text-center m-0 p-0">TECHSOUL CYBER SOLUTIONS</h2>
            <h5 class="text-center m-0 p-0">GSTIN : 32ADNPO8730B1ZO</h5>
            <h5 class="text-center m-0 p-0">OPP.TRUST HOSPITAL ROOM NO: 20/792, RM-VENTURES, RANDATHANI.PO</h5>
            <h1 class="text-center m-0 p-0 mt-10">Monthly Profit Summary - {{ $search_date }}</h1>
        </div>

        <table class="table w-100 mt-10" >
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Invoice No.</th>
                    <th>Customer Name</th>
                    <th>Product</th>
                    <th>Qty</th>
                    <th>Bill Amount<br>(inc.tax)</th>
                    <th>Rate of item</th>
                    <th>Purchase Amount</th>
                    <th>Profit</th>
                    <th>Service Charge</th>
                    <th>Total Amount<br>To Techsoul</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @php
                    $total_bill_amount = 0;
                    $total_rate_of_item = 0;
                    $total_purchase_amount = 0;
                    $total_profit_amount = 0;
                    $total_service_charge = 0;
                    $total_amount_to_techsoul = 0;
                    $total_paid_amount = 0;
                    $total_credit_amount = 0;
                @endphp
                @foreach ( $sales_details as $sales_detail)
                    @php
                        $sales_items = DB::table('sales_items')->where('sales_id',$sales_detail->id)->get();
                        $saleCount = DB::table('sales_items')->where('sales_id',$sales_detail->id)->count();
                        $t_qty = 0;
                        $t_bill_amount = 0;
                        $t_rate = 0;
                        $t_purchase_amount = 0;
                        $t_profit = 0;
                        $t_search_amount = 0;
                        $t_to_techsoul = 0;
                    @endphp
                    @foreach ( $sales_items as $item)
                        <tr>
                            <td>{{ $sales_detail->sales_date }}</td>
                            <td>{{ $sales_detail->invoice_number }}</td>
                            @php
                                $customers = DB::table('customers')->where('id',$sales_detail->customer_id)->first();
                                $daybook_details = DB::table('daybooks')->where('income_id','FROM_INVOICE')->where('job',$sales_detail->invoice_number)->first();
                            @endphp
                            <td>{{ $customers->name }}</td>
                            @if($item->product_id == '159' || $item->product_id == '162')
                                <td>SERVICE</td>
                                <td>NA</td>
                                @php
                                    $t_bill_amount += $item->sales_price;
                                    $t_search_amount += $item->sales_price;
                                @endphp
                                <td>{{ $item->sales_price }}</td>
                                <td>0</td>
                                <td>0</td>
                                <td>0</td>
                                <td>{{ $item->sales_price }}</td>
                                @if ($daybook_details)
                                    @php
                                        $total_paid_amount = $total_paid_amount+$item->sales_price;
                                    @endphp
                                @else
                                    @php
                                        $total_credit_amount = $total_credit_amount+$item->sales_price;
                                    @endphp
                                @endif
                                @php
                                    $total_bill_amount = $total_bill_amount+$item->sales_price;
                                    $total_profit = $item->sales_price;
                                    $total_service_charge = $total_service_charge + $item->sales_price;
                                @endphp
                            @else
                                @php
                                    $product_details = DB::table('products')->where('id',$item->product_id)->first();
                                    if($item->serial_number) {
                                        $product_name = $product_details->product_name . ' - [' . $item->serial_number . ']';
                                    }else{
                                        $product_name = $product_details->product_name;
                                    }
                                    $name_length = strlen($product_name);
                                @endphp
                                @if ($name_length > 30 && $name_length <= 60)
                                    @php
                                        $product_name1 = substr($product_name,0,30);
                                        $product_name2 = substr($product_name,30);
                                    @endphp
                                    <td>{{ $product_name1 }}<br>{{ $product_name2 }}</td>
                                @elseif($name_length > 60 && $name_length <= 90)
                                    @php
                                        $product_name1 = substr($product_name,0,30);
                                        $product_name2 = substr($product_name,30,30);
                                        $product_name3 = substr($product_name,60);
                                    @endphp
                                    <td>{{ $product_name1 }}<br>{{ $product_name2 }}<br>{{ $product_name3 }}</td>
                                @elseif($name_length > 90 && $name_length <= 120)
                                    @php
                                        $product_name1 = substr($product_name,0,30);
                                        $product_name2 = substr($product_name,30,30);
                                        $product_name3 = substr($product_name,60,30);
                                        $product_name4 = substr($product_name,90);
                                    @endphp
                                    <td>{{ $product_name1 }}<br>{{ $product_name2 }}<br>{{ $product_name3 }}<br>{{ $product_name4 }}</td>
                                @elseif($name_length > 120 && $name_length <= 150)
                                    @php
                                        $product_name1 = substr($product_name,0,30);
                                        $product_name2 = substr($product_name,30,30);
                                        $product_name3 = substr($product_name,60,30);
                                        $product_name4 = substr($product_name,90,30);
                                        $product_name5 = substr($product_name,120);
                                    @endphp
                                    <td>{{ $product_name1 }}<br>{{ $product_name2 }}<br>{{ $product_name3 }}<br>{{ $product_name4 }}<br>{{ $product_name5 }}</td>
                                @elseif($name_length > 150)
                                    @php
                                        $product_name1 = substr($product_name,0,30);
                                        $product_name2 = substr($product_name,30,30);
                                        $product_name3 = substr($product_name,60,30);
                                        $product_name4 = substr($product_name,90,30);
                                        $product_name5 = substr($product_name,120,30);
                                        $product_name6 = substr($product_name,150);
                                    @endphp
                                    <td>{{ $product_name1 }}<br>{{ $product_name2 }}<br>{{ $product_name3 }}<br>{{ $product_name4 }}<br>{{ $product_name5 }}<br>{{ $product_name6 }}</td>
                                @else
                                    <td>{{ $product_name }}</td>
                                @endif
                                @php
                                    $t_qty += $item->product_quantity;
                                @endphp
                                <td>{{ $item->product_quantity }}</td>
                                @php
                                $t_bill_amount += $item->sales_price;
                                @endphp
                                <td>{{ $item->sales_price }}</td>
                                @if($daybook_details)
                                    @php
                                        $total_paid_amount = $total_paid_amount+$item->sales_price;
                                    @endphp
                                @else
                                    @php
                                        $total_credit_amount = $total_credit_amount+$item->sales_price;
                                    @endphp
                                @endif
                                @php
                                    $total_bill_amount = $total_bill_amount+$item->sales_price;
                                    $total_rate_of_item = $total_rate_of_item+$item->sales_price;
                                @endphp
                                @php
                                    $t_rate += $item->sales_price;
                                @endphp
                                <td>{{ $item->sales_price }}</td>
                                @php
                                    $stock = DB::table('stocks')->where('product_id',$item->product_id)->first();
                                    $purchase_details = DB::table('purchase_items')->where('product_id',$item->product_id)->latest('id')->first();
                                    $purchase_amount_without_gst =( $stock->product_unit_price) * ($item->product_quantity);
                                    $purchase_tax_amount = $purchase_amount_without_gst * ($purchase_details->gst_percent/100);
                                    $purchase_amount = $purchase_amount_without_gst + $purchase_tax_amount;
                                    $purchase_amount = number_format($purchase_amount, 2, '.', '');
                                    $profit = ($item->sales_price) - $purchase_amount;
                                    $total_purchase_amount = $total_purchase_amount+$purchase_amount;
                                    $total_purchase_amount = number_format($total_purchase_amount, 2, '.', '');
                                    $total_profit_amount = $total_profit_amount+$profit;
                                @endphp
                                @php
                                    $t_purchase_amount += $purchase_amount;
                                    $t_profit += $profit;
                                @endphp
                                <td>{{ $purchase_amount }}</td>
                                <td>{{ $profit }}</td>
                                <td>0</td>
                                @php
                                    $total_profit = $profit;
                                @endphp
                            @endif
                            @php
                                $total_amount_to_techsoul = $total_amount_to_techsoul+$total_profit;
                                $t_to_techsoul += $total_profit;
                            @endphp
                            <td>{{ $total_profit }}</td>
                            @if ($daybook_details)
                                <td>PAID</td>
                            @else
                                <td>NOT PAID</td>
                            @endif
                        </tr>
                    @endforeach
                    @if($saleCount >0)
                    <tr>
                        <th colspan="4" style="text-align: center">Total</th>
                        <th>{{ $t_qty }}</th>
                        <th>{{ $t_bill_amount }}</th>
                        <th>{{ $t_rate }}</th>
                        <th>{{ $t_purchase_amount }}</th>
                        <th>{{ $t_profit }}</th>
                        <th>{{ $t_search_amount }}</th>
                        <th>{{ $t_to_techsoul }}</th>
                        <th></th>
                    </tr>
                    @endif
                @endforeach
                <tr>
                    <th colspan="5">Total</th>
                    <th>{{ $total_bill_amount }}</th>
                    <th>{{ $total_rate_of_item }}</th>
                    <th>{{ $total_purchase_amount }}</th>
                    <th>{{ $total_profit_amount }}</th>
                    <th>{{ $total_service_charge }}</th>
                    <th>{{ $total_amount_to_techsoul }}</th>
                    <th></th>
                </tr>
            </tbody>
        </table>
        <div>
            <h4 class="mt-25">Profit Summary</h4>
        </div>
        <table class="table w-50">
            <tr>
                <th></th>
                <th>Total</th>
                <th>Paid</th>
                <th>Credit</th>
            </tr>
            <tr>
                <th style="text-align: left">Total Income Against Invoice</th>
                <td>{{ $total_bill_amount }}</td>
                <td>{{ $total_paid_amount }}</td>
                <td>{{ $total_credit_amount }}</td>
            </tr>
            <tr>
                <th style="text-align: left">Total Income Against Product</th>
                <td>{{ $total_rate_of_item }}</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th style="text-align: left">Total Income/Profit Against Service</th>
                <td>{{ $total_service_charge }}</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th style="text-align: left">Total Expense Against Product</th>
                <td>{{ $total_purchase_amount }}</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th style="text-align: left">Total Profit Against Product</th>
                <td>{{ $total_profit_amount }}</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th style="text-align: left">Total Profit</th>
                <th style="text-align: left">{{ $total_amount_to_techsoul }}</th>
                <th style="text-align: left"></th>
                <th style="text-align: left"></th>
            </tr>
        </table>
        <div>
            <h4 class="mt-25">Expense</h4>
        </div>
        <table class="table w-50">
            <tr>
                <th>Item</th>
                <th>Amount</th>
            </tr>
            <tr>
                <th style="text-align: left">Total Expense</th>
                <td>{{ $total_expense }}</td>
            </tr>
            <tr>
                <th style="text-align: left">From Expense Category</th>
                <td>{{ $total_expense_category }}</td>
            </tr>
            <tr>
                <th style="text-align: left">From Deposit/Other Category</th>
                <td>{{ $total_deposit_category }}</td>
            </tr>
        </table>
        <div class="table-section bill-tbl w-100 mt-25">
            <table class="table w-50">
                <tr>
                    <th>Monthly Profit = Total Profit - Total Expense(from cat. expense)</th>
                </tr>
                @php
                    $monthly_profit = $total_amount_to_techsoul - $total_expense_category;
                @endphp
                <tr>
                    <th style="text-align: center">{{ $monthly_profit }}</th>
                </tr>
            </table>
        </div>
        <div>
            <h3 class="mt-25">Expense Summary</h3>
            <h4 class="mt-25">Expenses</h4>
        </div>
        <table class="table w-50">
            <tr>
                <th>Types</th>
                <th>Amount</th>
            </tr>
            @php
                $total_expense_category_amount = 0;
            @endphp
            @foreach ( $expense_categroy_expenses as $expenses)
                <tr>
                    <th style="text-align: left">{{ $expenses['name'] }}</th>
                    <td>{{ $expenses['amount'] }}</td>
                    @php
                        $total_expense_category_amount+=$expenses['amount'];
                    @endphp
                </tr>
            @endforeach
                <tr>
                    <th style="text-align: left">Total</th>
                    <th style="text-align: left">{{ $total_expense_category_amount }}</th>
                </tr>
        </table>
        <div>
            <h4 class="mt-25">Deposit/Others</h4>
        </div>
        <table class="table w-50">
            <tr>
                <th>Types</th>
                <th>Amount</th>
            </tr>
            @php
                $total_deposit_category_amount = 0;
            @endphp
            @foreach ( $deposit_categroy_expenses as $expenses)
                <tr>
                    <th style="text-align: left">{{ $expenses['name'] }}</th>
                    <td>{{ $expenses['amount'] }}</td>
                    @php
                        $total_deposit_category_amount+=$expenses['amount'];
                    @endphp
                </tr>
            @endforeach
                <tr>
                    <th style="text-align: left">Total</th>
                    <th style="text-align: left">{{ $total_deposit_category_amount }}</th>
                </tr>
        </table>
    </div>

    </body>
</html>
