<!DOCTYPE html>
<html>
<head>
    <title>Monthly Profit Summary - Hostee the Planner</title>
</head>
<style type="text/css">
    body{
        font-family: 'Roboto Condensed', sans-serif;
    }
    .container{
        bottom: 50px;
    }
    .m-0{
        margin: 0px;
    }
    .p-0{
        padding: 0px;
    }
    .pt-5{
        padding-top:5px;
    }
    .mt-10{
        margin-top:10px;
    }
    .mt-25{
        margin-top:25px;
    }
    .text-center{
        text-align:center !important;
    }
    .w-100{
        width: 100%;
    }
    .w-50{
        width:50%;
    }
    .w-85{
        width:85%;
    }
    .w-15{
        width:15%;
    }
    .logo img{
        width:45px;
        height:45px;
        padding-top:30px;
    }
    .logo span{
        margin-left:8px;
        top:19px;
        position: absolute;
        font-weight: bold;
        font-size:25px;
    }
    .gray-color{
        color:#5D5D5D;
    }
    .text-bold{
        font-weight: bold;
    }
    .border{
        border:1px solid black;
    }
    table tr,th,td{
        border: 1px solid #d2d2d2;
        border-collapse:collapse;
        padding:7px 8px;
    }
    table tr th{
        background: #F4F4F4;
        font-size:15px;
    }
    table tr td{
        font-size:13px;
    }
    table{
        border-collapse:collapse;
    }
    .box-text p{
        line-height:10px;
    }
    .float-left{
        float:left;
    }
    .total-part{
        font-size:16px;
        line-height:12px;
    }
    .total-right p{
        padding-right:20px;
    }
    .page-break {
        page-break-after: always;
    }
    .footer {
        position: fixed;
        bottom: -24px;
    }

    .footer .page:after {
        text-align:left;
        content: counter(page);
    }
    .footer .caption {
        text-align:right !important;
        font-size:10px;
    }
</style>
<body>
    <div class="footer">
        @php
            $printed_by = Auth::user()->name;
            $printed_on = Carbon\carbon::now();
        @endphp
        <table style="padding-top:20px;">
            <tr style="border:none;">
                <td style="border:none;">
                    <p class="page"></p>
                </td>
                <td style="border:none;">
                    <p class="caption">generated by {{ $printed_by }} on {{ $printed_on }}</p>
                </td>
            </tr>
        </table>
        </div>
    </div>
    <div class="container">
        <div class="head-title">
            <h2 class="text-center m-0 p-0">HOSTEE THE PLANNER</h2>
            {{-- <h5 class="text-center m-0 p-0">GSTIN : 32ADNPO8730B1ZO</h5> --}}
            <h5 class="text-center m-0 p-0">NEAR LANCOR CONCEPTS, CHERUSHOLA ROAD, SWAGATHAMAD</h5>
            <h1 class="text-center m-0 p-0 mt-10">Monthly Profit Summary - {{ $search_date }}</h1>
        </div>

        <table class="table w-100 mt-10" >
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Invoice No.</th>
                    <th>Customer Name</th>
                    <th>Product</th>
                    <th>Qty</th>
                    <th>Unit Price X Qty<br>(Bill Amount)</th>
                    <th>Purchase X Qty<br>(Bill Amount)</th>
                    <th>Margin</th>
                    <th>Service Charge</th>
                    <th>TAT</th>
                </tr>
            </thead>
            <tbody>
                @php
                    $total_bill_amount = 0;
                    $total_rate_of_item = 0;
                    $total_purchase_amount = 0;
                    $total_profit_amount = 0;
                    $total_service_charge = 0;
                    $total_amount_to_techsoul = 0;
                    $total_paid_amount = 0;
                    $total_credit_amount = 0;
                    $total_tat_amount = 0;
                @endphp
                @foreach ( $sales_details as $sales_detail)
                    @php
                        $sales_items = DB::table('sales_items')->where('sales_id',$sales_detail->id)->get();
                        $saleCount = DB::table('sales_items')->where('sales_id',$sales_detail->id)->count();
                        $t_qty = 0;
                        $t_bill_amount = 0;
                        $t_rate = 0;
                        $t_purchase_amount = 0;
                        $t_profit = 0;
                        $t_search_amount = 0;
                        $t_to_techsoul = 0;
                        $t_tat = 0;
                    @endphp
                    @foreach ( $sales_items as $item)
                        @php
                            $profit = 0;
                            $chiplevel_amount = 0;
                        @endphp

                        <tr>
                            <td>{{ $sales_detail->sales_date }}</td>
                            <td>{{ $sales_detail->invoice_number }}</td>
                            @php
                                $customers = DB::table('customers')->where('id',$sales_detail->customer_id)->first();
                                $daybook_details = DB::table('daybooks')->where('income_id','FROM_INVOICE')->where('job',$sales_detail->invoice_number)->first();
                            @endphp
                            <td>{{ $customers->name }}</td>
                            @if($item->product_id == '159' || $item->product_id == '162')
                                @php
                                    $product_details = DB::table('products')->where('id', $item->product_id)->first();
                                    if ($item->serial_number) {
                                        $product_name = $product_details->product_name . ' - [' . $item->serial_number . ']';
                                    } else {
                                        $product_name = $product_details->product_name;
                                    }
                                    $name_length = strlen($product_name);
                                @endphp
                                <td>
                                    {{-- @if ($name_length > 0)
                                        @for ($i = 0; $i < $name_length; $i += 25)
                                            {{ substr($product_name, $i, 25) }}<br>
                                        @endfor
                                    @else --}}
                                        {{ $product_name }}
                                    {{-- @endif --}}
                                </td>

                                <td>{{ $item->product_quantity }}</td>
                                @php
                                    $t_bill_amount += $item->sales_price;
                                    $t_search_amount += $item->sales_price;
                                    $t_qty += $item->product_quantity;
                                    $item_unit_price_gst = $item->unit_price  * ($item->gst_percent/100);
                                    $item_unit_price_gst_inc = $item->unit_price  + $item_unit_price_gst;
                                    $item_unit_price_gst_inc = number_format($item_unit_price_gst_inc, 2, '.', '');
                                @endphp
                                <td>{{ $item_unit_price_gst_inc }}X{{ $item->product_quantity }}<br><b>{{ $item->sales_price }}</b></td>

                                @php
                                    $consignment = DB::table('consignments')->where('invoice_no', $sales_detail->invoice_number)->first();
                                @endphp
                                @if ( $consignment )
                                    @php
                                        $chiplevels = DB::table('chiplevels')->where('jobcard_id', $consignment->id)->get();
                                        $chiplevel_amount = 0;
                                    @endphp
                                    @foreach ($chiplevels as $chiplevel)
                                        $chiplevel_amount += $chiplevel->service_charge;
                                    @endforeach
                                    <td>{{ $chiplevel_amount }}</td>
                                    @php
                                        $profit = $item->sales_price - $chiplevel_amount;
                                        $t_profit += $profit;
                                    @endphp
                                    <td>{{ $profit }}</td>
                                @else
                                    <td>0</td>
                                    <td>0</td>
                                @endif
                                <td>{{ $item->sales_price }}</td>
                                @if ($daybook_details)
                                    @php
                                        $total_paid_amount = $total_paid_amount + $item->sales_price;
                                    @endphp
                                @else
                                    @php
                                        $total_credit_amount = $total_credit_amount + $item->sales_price;
                                    @endphp
                                @endif
                                @php
                                    $total_bill_amount = $total_bill_amount + $item->sales_price;
                                    $total_profit = $item->sales_price;
                                    $total_service_charge = $total_service_charge + $item->sales_price;
                                @endphp
                            @else
                                @php
                                    $product_details = DB::table('products')->where('id', $item->product_id)->first();
                                    if ($item->serial_number) {
                                        $product_name = $product_details->product_name . ' - [' . $item->serial_number . ']';
                                    } else {
                                        $product_name = $product_details->product_name;
                                    }
                                    $name_length = strlen($product_name);
                                @endphp
                                <td>
                                    {{-- @if ($name_length > 0)
                                        @for ($i = 0; $i < $name_length; $i += 25)
                                            {{ substr($product_name, $i, 25) }}<br>
                                        @endfor
                                    @else --}}
                                        {{ $product_name }}
                                    {{-- @endif --}}
                                </td>

                                @php
                                    $t_qty += $item->product_quantity;
                                @endphp
                                <td>{{ $item->product_quantity }}</td>

                                @php
                                    $t_bill_amount += $item->sales_price;
                                    $item_unit_price_gst = $item->unit_price  * ($item->gst_percent/100);
                                    $item_unit_price_gst_inc = $item->unit_price  + $item_unit_price_gst;
                                    $item_unit_price_gst_inc = number_format($item_unit_price_gst_inc, 2, '.', '');
                                @endphp

                                <td>{{ $item_unit_price_gst_inc }}X{{ $item->product_quantity }}<br><b>{{ $item->sales_price }}</b></td>
                                @if($daybook_details)
                                    @php
                                        $total_paid_amount = $total_paid_amount+$item->sales_price;
                                    @endphp
                                @else
                                    @php
                                        $total_credit_amount = $total_credit_amount+$item->sales_price;
                                    @endphp
                                @endif
                                @php
                                    $total_bill_amount = $total_bill_amount+$item->sales_price;
                                    $total_rate_of_item = $total_rate_of_item+$item->sales_price;
                                @endphp
                                @php
                                    $t_rate += $item->sales_price;
                                @endphp

                                @php
                                    $stock = DB::table('stocks')->where('product_id',$item->product_id)->first();
                                    $purchase_details = DB::table('purchase_items')->where('product_id', $item->product_id)->latest('id')->first();
                                    $product = DB::table('products')->where('id', $item->product_id)->first();

                                    $product_price = $product->product_price ?? 0;
                                    $purchase_amount_without_gst =( $stock->product_unit_price);
                                    $purchase_tax_amount = $purchase_amount_without_gst * ($purchase_details->gst_percent/100);
                                    $purchase_amount = $purchase_amount_without_gst + $purchase_tax_amount;
                                    $purchase_amount = number_format($purchase_amount, 2, '.', '');
                                    $total_item_purchase_amount = $product_price * $item->product_quantity;
                                    $total_purchase_amount = $total_purchase_amount + $purchase_amount;
                                    $total_purchase_amount = number_format($total_purchase_amount, 2, '.', '');
                                    $profit = ($item->sales_price) - $total_item_purchase_amount;
                                    $total_profit_amount = $total_profit_amount+$profit;
                                @endphp
                                @php
                                    $t_purchase_amount += $purchase_amount;
                                    $t_profit += $profit;
                                @endphp
                                <td>{{ number_format($product_price, 2, '.', '') }}X{{ $item->product_quantity }}<br><b>{{ $total_item_purchase_amount }}</b></td>
                                <td>{{ number_format($profit, 2, '.', '') }}</td>
                                <td>0</td>
                                @php
                                    $total_profit = $profit;
                                @endphp
                            @endif

                            @php
                                $profit = isset($profit) ? $profit : 0;
                                $chiplevel_amount = isset($chiplevel_amount) ? $chiplevel_amount : 0;

                                $service_charge_value = ($item->product_id == '159' || $item->product_id == '162')
                                    ? $item->sales_price
                                    : 0;

                                $profit = is_numeric($profit) ? $profit : 0;

                                $tat = $profit + $service_charge_value;
                                $t_tat += $tat;
                            @endphp
                            <td>{{ number_format($tat, 2, '.', '') }}</td>
                        </tr>
                    @endforeach
                    @if($saleCount >0)
                    <tr>
                        <th colspan="4" style="text-align: center">Total</th>
                        <th style="font-weight: 400">{{ $t_qty }}</th>
                        <th style="font-weight: 400">{{ number_format($t_bill_amount, 2, '.', '') }}</th>
                        <th style="font-weight: 400">{{ number_format($t_purchase_amount, 2, '.', '') }}</th>
                        <th style="font-weight: 400">{{ number_format($t_profit, 2, '.', '') }}</th>
                        <th style="font-weight: 400">{{ number_format($t_search_amount, 2, '.', '') }}</th>
                        <th>{{ number_format($t_tat, 2, '.', '') }}</th>
                    </tr>
                    @php
                        $total_tat_amount += $t_tat;
                    @endphp
                    @endif
                @endforeach
                <tr>
                    <th colspan="5">Total</th>
                    <th>{{ number_format($total_bill_amount, 2, '.', '') }}</th>
                    <th>{{ number_format($total_purchase_amount, 2, '.', '') }}</th>
                    <th>{{ number_format($total_profit_amount, 2, '.', '') }}</th>
                    <th>{{ number_format($total_service_charge, 2, '.', '') }}</th>
                    <th>{{ number_format($total_tat_amount, 2, '.', '') }}</th>
                </tr>
            </tbody>
        </table>
        <div>
            <h4 class="mt-25">Profit Summary</h4>
        </div>
        <table class="table w-50">
            <tr>
                <th></th>
                <th>Total</th>
                <th>Paid</th>
                <th>Credit</th>
            </tr>
            <tr>
                <th style="text-align: left">Total Income Against Invoice</th>
                <td>{{ $total_bill_amount }}</td>
                <td>{{ $total_paid_amount }}</td>
                <td>{{ $total_credit_amount }}</td>
            </tr>
            <tr>
                <th style="text-align: left">Total Income Against Product</th>
                <td>{{ $total_rate_of_item }}</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th style="text-align: left">Total Income/Profit Against Service</th>
                <td>{{ $total_service_charge }}</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th style="text-align: left">Total Expense Against Product</th>
                <td>{{ $total_purchase_amount }}</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th style="text-align: left">Total Profit Against Product</th>
                <td>{{ $total_profit_amount }}</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th style="text-align: left">Total Profit</th>
                <th style="text-align: left">{{ $total_amount_to_techsoul }}</th>
                <th style="text-align: left"></th>
                <th style="text-align: left"></th>
            </tr>
        </table>
        <div>
            <h4 class="mt-25">Expense</h4>
        </div>
        <table class="table w-50">
            <tr>
                <th>Item</th>
                <th>Amount</th>
            </tr>
            <tr>
                <th style="text-align: left">Total Expense</th>
                <td>{{ $total_expense }}</td>
            </tr>
            <tr>
                <th style="text-align: left">From Expense Category</th>
                <td>{{ $total_expense_category }}</td>
            </tr>
            <tr>
                <th style="text-align: left">From Deposit/Other Category</th>
                <td>{{ $total_deposit_category }}</td>
            </tr>
        </table>
        <div class="table-section bill-tbl w-100 mt-25">
            <table class="table w-50">
                <tr>
                    <th>Monthly Profit = Total Profit - Total Expense(from cat. expense)</th>
                </tr>
                @php
                    $monthly_profit = $total_amount_to_techsoul - $total_expense_category;
                @endphp
                <tr>
                    <th style="text-align: center">{{ $monthly_profit }}</th>
                </tr>
            </table>
        </div>
        <div>
            <h3 class="mt-25">Expense Summary</h3>
            <h4 class="mt-25">Expenses</h4>
        </div>
        <table class="table w-50">
            <tr>
                <th>Types</th>
                <th>Amount</th>
            </tr>
            @php
                $total_expense_category_amount = 0;
            @endphp
            @foreach ( $expense_categroy_expenses as $expenses)
                <tr>
                    <th style="text-align: left">{{ $expenses['name'] }}</th>
                    <td>{{ $expenses['amount'] }}</td>
                    @php
                        $total_expense_category_amount+=$expenses['amount'];
                    @endphp
                </tr>
            @endforeach
                <tr>
                    <th style="text-align: left">Total</th>
                    <th style="text-align: left">{{ $total_expense_category_amount }}</th>
                </tr>
        </table>
        <div>
            <h4 class="mt-25">Deposit/Others</h4>
        </div>
        <table class="table w-50">
            <tr>
                <th>Types</th>
                <th>Amount</th>
            </tr>
            @php
                $total_deposit_category_amount = 0;
            @endphp
            @foreach ( $deposit_categroy_expenses as $expenses)
                <tr>
                    <th style="text-align: left">{{ $expenses['name'] }}</th>
                    <td>{{ $expenses['amount'] }}</td>
                    @php
                        $total_deposit_category_amount+=$expenses['amount'];
                    @endphp
                </tr>
            @endforeach
                <tr>
                    <th style="text-align: left">Total</th>
                    <th style="text-align: left">{{ $total_deposit_category_amount }}</th>
                </tr>
        </table>
    </div>

    </body>
</html>
